### ISSUE TITLE
Beta branch?

### ISSUE THREAD

**Issue by swsnr** [flathub/re.chiaki.Chiaki#13]
Chiaki has seen some [recent activity](https://git.sr.ht/~thestr4ng3r/chiaki/log/master), in particular [commit 4c820976](https://git.sr.ht/~thestr4ng3r/chiaki/commit/4c8209762c1f822d2066367062170f47692abd54), which apparently enables support for more controllers than just the standard PS controller.

I'd very much like to try this, since I'd like to use my Nacon controller for remote play too.

I wouldn't like to point this manifest to an unreleased commit directly, but as I understand flathub we can create a `beta` branch which then ends up in the Flathub Beta repository.

@AsciiWolf @iMonZ Do you have objections?  If not I'd try this somewhat soon'ish 🙂

**Comment by AsciiWolf** [comment]
No objections from my side. :-)

**Comment by swsnr** [comment]
Thanks, I've created the branch.
