### ISSUE TITLE
EOL this Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/re.chiaki.Chiaki#22]
The original Chiaki was basically replaced by its newer fork [io.github.streetpea.Chiaki4deck](https://github.com/flathub/io.github.streetpea.Chiaki4deck). Consider EOLing this Flatpak.

**Comment by swsnr** [comment]
Let's do this :+1:  Seems pretty easy according to https://docs.flathub.org/docs/for-app-authors/maintenance/#end-of-life

**Comment by AsciiWolf** [comment]
#23
