### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by iMonZ** [flathub/re.chiaki.Chiaki#3]
Doesn't start on Manjaro.

Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

env: QT_QPA_PLATFORM=WAYLAND

**Comment by AsciiWolf** [comment]
Interesting. It works fine on my Fedora 35 Workstation system with Wayland GNOME session.

**Comment by iMonZ** [comment]
Fixed it!

**Comment by iMonZ** [comment]
> Interesting. It works fine on my Fedora 35 Workstation system with Wayland GNOME session.

Check if you are really running Wayland and not XWayland

**Comment by AsciiWolf** [comment]
I am running XWayland. The native wayland socket is disabled on purpose. When I last tried Chiaki on native Wayland, it had multiple issues, at least on GNOME.

**Comment by iMonZ** [comment]
> I am running XWayland. The native wayland socket is disabled on purpose. When I last tried Chiaki on native Wayland, it had multiple issues, at least on GNOME.

Which issues? I tried it with full Wayland and saw no issues.

**Comment by AsciiWolf** [comment]
I remember that there were some stream-related problems and maybe some controller issues. However, I don't remember it exactly. I am a big Wayland supporter and usually try to enable native Wayland support for all my Flatpaks if possible. If I don't it is because of some blocking issues that are not easy to fix/workaround. Anyway, sorry, I probably won't have enough time in upcoming weeks to work on this issue. By the way, are you using GNOME or KDE?

**Comment by iMonZ** [comment]
> I remember that there were some stream-related problems and maybe some controller issues. However, I don't remember it exactly. I am a big Wayland supporter and usually try to enable native Wayland support for all my Flatpaks if possible. If I don't it is because of some blocking issues that are not easy to fix/workaround. Anyway, sorry, I probably won't have enough time in upcoming weeks to work on this issue. By the way, are you using GNOME or KDE?

Im using gnome
Currently I’m installing fedora 36 on my second machine and I will try it there and check if something is missing.

**Comment by AsciiWolf** [comment]
What GPU are you using? I remember that Nvidia had problems with XWayland.

**Comment by iMonZ** [comment]
> What GPU are you using? I remember that Nvidia had problems with XWayland.

Yeah that’s why I disabled XWayland with my PR.
XWayland makes problems everywhere and should be avoided.
Nvidia had problems with Wayland itself but these are solved in 2021.

**Comment by iMonZ** [comment]
> > What GPU are you using? I remember that Nvidia had problems with XWayland.
> 
> Yeah that’s why I disabled XWayland with my PR. XWayland makes problems everywhere and should be avoided. Nvidia had problems with Wayland itself but these are solved in 2021.

Radeon rx 580
