### ISSUE TITLE
org.kde.Platform//5.15 is EOL

### ISSUE THREAD

**Issue by TheHooly** [flathub/re.chiaki.Chiaki#5]
```
[user@silverblue-laptop ~]$ flatpak update
Looking for updates…
Info: org.kde.Platform//5.15 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   re.chiaki.Chiaki
```

**Comment by AsciiWolf** [comment]
Thanks. I have [made a PR](https://github.com/flathub/re.chiaki.Chiaki/pull/6) with the runtime updated. Are you able to test it? I sadly don't have my PlayStation anymore (I am looking for a new maintainers of this repo, btw.).
