### ISSUE TITLE
Black screen while in fullscreen mode

### ISSUE THREAD

**Issue by Daniel6372** [flathub/re.chiaki.Chiaki#8]
After last week's update (2022-12-14), the screen is black 100% of the time while in fullscreen.
Another issue that might be related is that the cursor gets hidden while highlighting the window close button (while in windowed mode of course).

**Comment by Daniel6372** [comment]
Forgot to mention:
Distro is Fedora Linux 37 (Workstation Edition) x86_64
Using Intel integrated Iris Xe graphics, issue persists regardless of hardware decode option

**Comment by swsnr** [comment]
What's your desktop environment? Do you use Wayland?

**Comment by Daniel6372** [comment]
Yes, using the default GNOME Wayland session.

**Comment by swsnr** [comment]
Can you fix the issue if you remove the permission for the Wayland socket and add the x11 socket instead?  You can use the flatseal app to change permissions of flatpaks per user

**Comment by Daniel6372** [comment]
Yep, that fixes it. Works exactly as before now.

**Comment by AsciiWolf** [comment]
Yeah, I had similar issues with Chiaki on native Wayland. That's why I did not enable the wayland socket for this Flatpak. However, I am not able to do any further testing since I don't have my PS4 anymore.

**Comment by swsnr** [comment]
Could you, just out of curiosity, check if the same happens if you use a native build of chiaki?  If it's buggy too under Wayland I think you should report this issue upstream to Chiaki itself…


In any case I'll revert the Wayland change, and make a ticket to try again in e.g. a year or with the next chiaki release.

**Comment by swsnr** [comment]
@AsciiWolf That said, I just realized that Chiaki builds SDL2 itself, and uses a version from two years ago.  Before I revert the Wayland permission change, I'd like to test a more recent SDL version 🙂

**Comment by swsnr** [comment]
@AsciiWolf @Daniel6372 See #9

**Comment by swsnr** [comment]
@Daniel6372 Could you check the build in #9?

**Comment by swsnr** [comment]
@Daniel6372 So #11 undoes the wayland changes, and should fix this issue.
